server:
  port: 8090

spring:
  datasource:
    username: lzw
    password: 123
    url: jdbc:mysql://47.102.219.1:3306/FuChuang?serverTimezone=Asia/Shanghai
  jackson:
    property-naming-strategy: CAMEL_CASE_TO_LOWER_CASE_WITH_UNDERSCORES
  redis:
    host: 47.114.1.149
    port: 6379
mybatis:
  mapper-locations: mapper/*
  configuration:
    map-underscore-to-camel-case: true

logging:
  level:
    com:
      jnlzw:
        java:
          mapper: debug # 显示sql语句和结果，只显示sql语句可设置为debug



